package com.ductho.nguphaptienganh.CacBaiHoc;

import android.webkit.WebView;

public class ThemThanhNgu {
    WebView wv;

    public ThemThanhNgu(WebView wv) {
        this.wv = wv;
        load();
    }
    private void load() {
        String html = "<h3><span style=\"color: #ff6600;\">1. Tục ngữ, th&agrave;nh ngữ:</span></h3>\n" +
                "<p>- Better safe than sorry: Cẩn tắc v&ocirc; &aacute;y n&aacute;y</p>\n" +
                "<p>- Money is the good servant but a bad master: Kh&ocirc;n lấy của che th&acirc;n, dại lấy th&acirc;n che của<br /><br />- The grass are allways green on the other side of the fence: Đứng n&uacute;i n&agrave;y tr&ocirc;ng n&uacute;i nọ<br /><br />- One bitten, twice shy: Chim phải đạn sợ c&agrave;nh cong<br /><br />- In rome do as Romans do: Nhập gia t&ugrave;y tục<br /><br />- Honesty is the best policy: Thật th&agrave; l&agrave; thượng s&aacute;ch</p>\n" +
                "<p>- A woman gives and forgives, a man gets and forgets: Đ&agrave;n b&agrave; cho v&agrave; tha thứ, đ&agrave;n &ocirc;ng nhận v&agrave; qu&ecirc;n<br /><br />- No roses without a thorn: Hồng n&agrave;o m&agrave; chẳng c&oacute; gai, việc n&agrave;o m&agrave; chẳng c&oacute; v&agrave;i kh&oacute; khăn!<br /><br />- It never rains but it pours: Ph&uacute;c bất tr&ugrave;ng lai ( họa v&ocirc; đơn ch&iacute; )<br /><br />- Save for the rainny day: L&agrave;m khi l&agrave;nh để d&agrave;nh khi đau<br /><br />- It's an ill bird that fouls its own nest: Vạch &aacute;o cho người xem lưng / Tốt đẹp ph&ocirc; ra xấu xa đậy lại.<br /><br />- Don't trouble trouble till trouble troubles you: Tr&aacute;nh voi chẳng xấu mặt n&agrave;o.<br /><br />- Still water run deep: T&acirc;m ngẩm tầm ngầm m&agrave; đấm chết voi<br /><br />- Men make house, women make home: Đ&agrave;n &ocirc;ng x&acirc;y nh&agrave;, đ&agrave;n b&agrave; x&acirc;y tổ ấm<br /><br />- East or west - home is best: Ta về ta tắm ao ta ( Kh&ocirc;ng đ&acirc;u tốt bằng ở nh&agrave; )<br /><br />- Many a little makes a mickle: Kiến tha l&acirc;u đầy tổ<br /><br />- Penny wise pound foolish: Tham b&aacute;t bỏ m&acirc;m</p>\n" +
                "<p>- Money make the mare go: C&oacute; tiền mua ti&ecirc;n cũng được<br /><br />- Like father, like son: Con nh&agrave; t&ocirc;ng kh&ocirc;ng giống l&ocirc;ng th&igrave; cũng giống c&aacute;nh<br /><br />- Beauty is in the eye of the beholder: Giai nh&acirc;n chỉ đẹp trong mắt người h&ugrave;ng.<br /><br />- The die is cast: B&uacute;t sa g&agrave; chết<br /><br />- Two can play that game: Ăn miếng trả miếng<br /><br />- Love is blind: T&igrave;nh y&ecirc;u m&ugrave; qu&aacute;ng<br /><br />- So far so good: Mọi thứ vẫn tốt đẹp<br /><br />- Practice makes perfect: C&oacute; c&ocirc;ng m&agrave;i sắt c&oacute; ng&agrave;y n&ecirc;n kim<br /><br />- Silence is gold: Im lặng l&agrave; v&agrave;ng<br /><br />- The more the merrier: C&agrave;ng đ&ocirc;ng c&agrave;ng vui<br /><br />- Time is money: Thời gian l&agrave; tiền bạc<br /><br />- The truth will out: C&aacute;i kim trong bọc c&oacute; ng&agrave;y l&ograve;i ra<br /><br />- Walls have ear: Tường c&oacute; v&aacute;ch<br /><br />- Everyone has their price: Con người cũng c&oacute; gi&aacute; của n&oacute;<br /><br />- It's a small world: Quả đất tr&ograve;n<br /><br />- You're only young once: Miệng c&ograve;n h&ocirc;i sữa<br /><br />- Ignorance is bliss: Kh&ocirc;ng biết th&igrave; dựa cột m&agrave; nghe<br /><br />- No pain, no gain: C&oacute; l&agrave;m th&igrave; mới c&oacute; ăn<br /><br />- A swallow cant make a summer: Một con &eacute;n ko l&agrave;m nổi m&ugrave;a xu&acirc;n<br /><br />- A bad beginning makes a bad ending: Đầu xu&ocirc;i đu&ocirc;i lọt.<br /><br />- A clean fast is better than a dirty breakfast: Giấy r&aacute;ch phải giữ lấy lề.<br /><br />- Barking dogs seldom bite: Ch&oacute; sủa ch&oacute; kh&ocirc;ng cắn.</p>\n" +
                "<p>- Beauty is but skin-deep: C&aacute;i nết đ&aacute;nh chết c&aacute;i đẹp.<br /><br />- Calamity is man's true touchstone: Lửa thử v&agrave;ng, gian nan thử sức.<br /><br />- Catch the bear before tou sell his skin: Chưa đỗ &ocirc;ng Ngh&egrave; đ&atilde; đe h&agrave;ng tổng<br /><br />- Diamond cut diamond: Vỏ qu&yacute;t d&agrave;y c&oacute; m&oacute;ng tay nhọn<br /><br />- Diligence is the mother succees: C&oacute; c&ocirc;ng m&agrave;i sắt c&oacute; ng&agrave;y n&ecirc;n kim<br /><br />- Each bird loves to hear himself sing: M&egrave;o khen m&egrave;o d&agrave;i đu&ocirc;i<br /><br />- Far from eye, far from heart: Xa mặt c&aacute;ch l&ograve;ng<br /><br />- Fine words butter no parsnips: C&oacute; thực mới vực được đạo<br /><br />- Give him an inch and he will take a yard: Được voi, đ&ograve;i ti&ecirc;n<br /><br />- Grasp all, lose all: Tham th&igrave; th&acirc;m<br /><br />- Habit cures habit: Dĩ độc trị độc<br /><br />- Haste makes waste Dục tốc bất đạt<br /><br />- Robbing a cradle: Tr&acirc;u gi&agrave; m&agrave; gặm cỏ non<br /><br />- Raining cats and dogs = Rain like pouring the water: Mưa như tr&uacute;t nước<br /><br />- A stranger nearby is better than a far-away relative: B&agrave; con xa kh&ocirc;ng bằng l&aacute;ng giềng gần<br /><br />- Tell me who's your friend and I'll tell you who you are: H&atilde;y n&oacute;i cho t&ocirc;i biết bạn của anh l&agrave; ai, t&ocirc;i sẽ n&oacute;i cho anh biết anh l&agrave; người như thế n&agrave;o<br /><br />- Time and tide wait for no man: Thời gian v&agrave; nước thủy triều kh&ocirc;ng đợi ai cả.<br /><br />- Silence is golden: Im lặng l&agrave; v&agrave;ng<br /><br />- Don't judge a book by its cover: Đừng tr&ocirc;ng mặt m&agrave; bắt h&igrave;nh dong<br /><br />- The tongue has no bone but it breaks bone: C&aacute;i lưỡi kh&ocirc;ng xương đ&ocirc;i đường lắt l&eacute;o<br /><br />- You will reap what you will sow: Gieo nh&acirc;n n&agrave;o gặt quả nấy</p>\n" +
                "<p>- A wolf won't eat wolf: Ch&oacute; s&oacute;i kh&ocirc;ng bao giờ ăn thịt đồng loại<br /><br />- Don't postpone until tomorrow what you can do today:&nbsp;Đừng để những việc cho ng&agrave;y mai m&agrave; bạn c&oacute; thể l&agrave;m h&ocirc;m nay</p>\n" +
                "<h3><span style=\"color: #ff6600;\">2. Ca dao:</span></h3>\n" +
                "<p>- Flat wine can cause drunkenness with large consumption Great speakers can create boredom with lengthy orations :&nbsp;Rượu nhạt uống lắm cũng say. Người hay n&oacute;i lắm dẩu hay cũng nh&agrave;m<br /><br />- True gold is to be tested with coal and fire Good bells by how they reverberate, good people by how they verbalize: V&agrave;ng th&igrave; thử lửa thử than Chu&ocirc;ng k&ecirc;u thử tiếng, người ngoan thử lời<br /><br />- Compliments to whoever built this leaden bell Wonderfully shaped like a real one except for being mute: Khen ai kh&eacute;o đ&uacute;c chu&ocirc;ng ch&igrave;. Dạng th&igrave; c&oacute; dạng, đ&aacute;nh th&igrave; kh&ocirc;ng k&ecirc;u.<br /><br />- If a cockatiel chose a pelican to mess with, He will beg for mercy when starting to get hit: Chim ch&iacute;ch m&agrave; ghẹo bồ n&ocirc;ng. Đến khi n&oacute; mổ, lạy &ocirc;ng t&ocirc;i chừa.<br /><br />- East or west-home is best: Ta về ta tắm ao ta D&ugrave; trong d&ugrave; đục ao nh&agrave; vẫn hơn</p>";
        wv.loadDataWithBaseURL(null, html, "text/html", "utf-8", null);
    }
}
